version: '1.0'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=argen
      - POSTGRES_USER=admin
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
  app: 
    image: test2
    ports:
      - 3500:3500